version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    environment:
      RMQADDR: rmq
      RMQUSER: guest
      RMQPASS: guest
      RMQPORT: 5672
    depends_on:
      - rmq
    restart: "on-failure"

  backend:
    build: ./backend
    ports:
      - "3000:4000"
    environment:
      RMQADDR: rmq
      RMQUSER: guest
      RMQPASS: guest
      RMQPORT: 5672
    depends_on:
      - rmq
    restart: "on-failure"

  rmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"